config/routes.rb
Rails.application.routes.draw do
  get 'dump_table/index'
  get 'dump_table/search'
  post 'dump_table/search'

  root to: 'visitors#index'

  devise_for :users

  resources :brands do
    resources :bodies do
      resources :engines do
        resources :ecus do
          resources :dumps
        end
      end
    end
  end
end

app/models/engine.rb
# == Schema Information
#
# Table name: engines
#
#  id         :integer          not null, primary key
#  name       :string
#  body_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Engine < ActiveRecord::Base
  belongs_to :body
  has_many :ecus
  validates :name, :body_id, presence: true
end

app/controllers/engines_controller.rb
# == Schema Information
#
# Table name: engines
#
#  id         :integer          not null, primary key
#  name       :string
#  body_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EnginesController < ApplicationController
  def index
    @body = Body.find(params[:body_id])
    @engines = @body.engines
  end

  def show
    redirect_to brand_body_engine_ecus_path params[:brand_id], params[:id]
  end

  def new
    @engine = Engine.new(body: Body.find(params[:body_id]))
    authorize @engine
  end

  def create
    @engine = Engine.new engine_params
    authorize @engine
    if @engine.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @engine = Engine.find params[:id]
    authorize @engine
  end

  def update
    @engine = Engine.find params[:id]
    authorize @engine
    if @engine.update engine_params
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @engine = Engine.find params[:id]
    authorize @engine
    @engine.destroy
    redirect_to brand_body_engines_path
  end

  def engine_params
    params.require(:engine).permit(:name).merge(body_id: params[:body_id])
  end
end

app/helpers/engines_helper.rb
# == Schema Information
#
# Table name: engines
#
#  id         :integer          not null, primary key
#  name       :string
#  body_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module EnginesHelper
end

app/views/engines/_form.html.slim
= simple_form_for [@engine.body.brand, @engine.body, @engine] do |f|
  = f.input :name, label: 'Name of Engine'
  = f.button :submit, class: 'btn-primary'

app/views/engines/edit.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li.active Update

= render 'form'

app/views/engines/index.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path(@body.brand)
  li.active Engines

.row.col-md-12
  p.lead
   => @body.brand.name
   = @body.name

- if policy(@engines).create?
  .row.col-md-12
    = link_to :new, new_brand_body_engine_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Name
        th Ecus
        - if policy(@engines).edit?
          th Edit
        - if policy(@engines).destroy?
          th Remove
    tbody
      - for engine in @engines do
        tr
          td = engine.id
          td = engine.name
          td = link_to :Ecus, brand_body_engine_ecus_path(engine.body.brand, engine.body, engine), class: 'btn btn-default'
          - if policy(@engines).edit?
            td = link_to :Edit, edit_brand_body_engine_path(engine.body.brand, engine.body, engine), class: 'btn btn-primary'
          - if policy(@engines).destroy?
            td = link_to :Remove, brand_body_engine_path(engine.body.brand, engine.body, engine), method: :delete, class: 'btn btn-danger'

app/views/engines/new.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li.active New

= render 'form'