config/routes.rb
Rails.application.routes.draw do
  get 'dump_table/index'
  get 'dump_table/search'
  post 'dump_table/search'

  root to: 'visitors#index'

  devise_for :users

  resources :brands do
    resources :bodies do
      resources :engines do
        resources :ecus do
          resources :dumps
        end
      end
    end
  end
end

app/models/body.rb
# == Schema Information
#
# Table name: bodies
#
#  id         :integer          not null, primary key
#  name       :string
#  brand_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Body < ActiveRecord::Base
  belongs_to :brand
  has_many :engines
  validates :name, :brand_id, presence: true
end

app/controllers/bodies_controller.rb
# == Schema Information
#
# Table name: bodies
#
#  id         :integer          not null, primary key
#  name       :string
#  brand_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BodiesController < ApplicationController
  def index
    @brand = Brand.find(params[:brand_id])
    @bodies = @brand.bodies
  end

  def show
    redirect_to brand_body_engines_path params[:brand_id], params[:id]
  end

  def new
    @body = Body.new(brand: Brand.find(params[:brand_id]))
    authorize @body
  end

  def create
    @body = Body.new body_params
    authorize @body
    if @body.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @body = Body.find params[:id]
    authorize @body
  end

  def update
    @body = Body.find params[:id]
    authorize @body
    if @body.update body_params
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @body = Body.find params[:id]
    authorize @body
    @body.destroy
    redirect_to brand_bodies_path
  end

  def body_params
    params.require(:body).permit(:name).merge(brand_id: params[:brand_id])
  end
end

app/helpers/bodies_helper.rb
# == Schema Information
#
# Table name: bodies
#
#  id         :integer          not null, primary key
#  name       :string
#  brand_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module BodiesHelper
end

app/views/bodies/_form.html.slim
= simple_form_for [@body.brand, @body] do |f|
  = f.input :name, label: 'Name of Body'
  = f.button :submit, class: 'btn-primary'

app/views/bodies/edit.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li.active Update

= render 'form'

app/views/bodies/index.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li.active Bodies

.row.col-md-12
  p.lead = @brand.name

- if policy(@bodies).create?
  .row.col-md-12
    = link_to :new, new_brand_body_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Name
        th Engines
        - if policy(@bodies).edit?
          th Edit
        - if policy(@bodies).destroy?
          th Remove
    tbody
      - for body in @bodies do
        tr
          td = body.id
          td = body.name
          td = link_to :Engines, brand_body_path(body.brand, body), class: 'btn btn-default'
          - if policy(@bodies).edit?
            td = link_to :Edit, edit_brand_body_path(body.brand, body), class: 'btn btn-primary'
          - if policy(@bodies).destroy?
            td = link_to :Remove, brand_body_path(body.brand, body), method: :delete, class: 'btn btn-danger'

app/views/bodies/new.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li.active New

= render 'form'