config/routes.rb
Rails.application.routes.draw do
  get 'dump_table/index'
  get 'dump_table/search'
  post 'dump_table/search'

  root to: 'visitors#index'

  devise_for :users

  resources :brands do
    resources :bodies do
      resources :engines do
        resources :ecus do
          resources :dumps
        end
      end
    end
  end
end

app/models/dump.rb
# == Schema Information
#
# Table name: dumps
#
#  id           :integer          not null, primary key
#  ecu_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  hw           :string
#  sw           :string
#  content      :integer          not null
#  content_size :integer
#

class Dump < ActiveRecord::Base
  belongs_to :ecu
  validates :content, :content_size, :ecu_id, presence: true
  validates :content, file_size: { less_than: 5.megabytes }

  mount_uploader :content, DumpUploader

  before_validation :set_content_size, on: [:create, :update]

  scope :search_hw, -> (query) { where('hw ILIKE ?', "%#{query}%") if query.present? }
  scope :search_sw, -> (query) { where('sw ILIKE ?', "%#{query}%") if query.present? }
  scope :search_ecu, -> (query) { joins(:ecu).where('ecus.name ILIKE ?', "%#{query}%") if query.present? }
  scope :search_engine, -> (query) { joins(ecu: :engine).where('engines.name ILIKE ?', "%#{query}%") if query.present? }
  scope :search_body, lambda { |query|
    joins(ecu: { engine: :body }).where('bodies.name ILIKE ?', "%#{query}%") if query.present?
  }
  scope :search_brand, lambda { |query|
    joins(ecu: { engine: { body: :brand } }).where('brands.name ILIKE ?', "%#{query}%") if query.present?
  }

  private

  def set_content_size
    self.content_size = content.file.size if content.present? && content_changed?
  end
end

app/controllers/dumps_controller.rb
# == Schema Information
#
# Table name: dumps
#
#  id           :integer          not null, primary key
#  ecu_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  hw           :string
#  sw           :string
#  content      :integer          not null
#  content_size :integer
#

class DumpsController < ApplicationController
  def index
    @ecu = Ecu.find(params[:ecu_id])
    @dumps = @ecu.dumps
  end

  def show
    dump = Dump.find params[:id]
    authorize dump
    send_data dump.content.file.read, filename: "#{dump.hw}-#{dump.sw}"
  end

  def new
    @dump = Dump.new(ecu: Ecu.find(params[:ecu_id]))
    authorize @dump
  end

  def create
    @dump = Dump.new dump_params
    authorize @dump
    if @dump.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @dump = Dump.find params[:id]
    authorize @dump
  end

  def update
    @dump = Dump.find params[:id]
    authorize @dump
    if @dump.update dump_params
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @dump = Dump.find params[:id]
    authorize @dump
    @dump.destroy
    redirect_to brand_body_engine_ecu_dumps_path
  end

  def dump_params
    params.require(:dump).permit(:hw, :sw, :content).merge(ecu_id: params[:ecu_id])
  end
end

app/helpers/dumps_helper.rb
# == Schema Information
#
# Table name: dumps
#
#  id           :integer          not null, primary key
#  ecu_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  hw           :string
#  sw           :string
#  content      :integer          not null
#  content_size :integer
#

module DumpsHelper
end

app/views/dumps/_form.html.slim
.row.col-md-12
  p.lead
   => @dump.ecu.engine.body.brand.name
   => @dump.ecu.engine.body.name
   => @dump.ecu.engine.name
   => @dump.ecu.name

.row.col-md-12
  = simple_form_for [@dump.ecu.engine.body.brand, @dump.ecu.engine.body, @dump.ecu.engine, @dump.ecu, @dump], multipart: true do |f|
    = f.input :hw, label: 'HW'
    = f.input :sw, label: 'SW'
    = f.input :content, as: :file, label: 'File'
    = f.button :submit, class: 'btn-primary'

app/views/dumps/edit.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li = link_to 'Ecus', brand_body_engine_ecus_path
  li = link_to 'Dumps', brand_body_engine_ecu_dumps_path
  li.active Update

= render 'form'

app/views/dumps/index.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path(@ecu.engine.body)
  li = link_to 'Engines', brand_body_engines_path(@ecu.engine.body.brand, @ecu.engine.body)
  li = link_to 'Ecus', brand_body_engine_ecus_path(@ecu.engine.body.brand, @ecu.engine.body, @ecu.engine)
  li.active Dumps

.row.col-md-12
  p.lead
   => @ecu.engine.body.brand.name
   => @ecu.engine.body.name
   => @ecu.engine.name
   => @ecu.name

- if policy(@dumps).create?
  .row.col-md-12
    = link_to :new, new_brand_body_engine_ecu_dump_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th HW
        th SW
        th Download
        - if policy(@dumps).edit?
          th Edit
        - if policy(@dumps).destroy?
          th Remove
    tbody
      - for dump in @dumps do
        tr
          td = dump.id
          td = dump.hw
          td = dump.sw
          td = link_to :Download, brand_body_engine_ecu_dump_path(dump.ecu.engine.body.brand, dump.ecu.engine.body, dump.ecu.engine, dump.ecu, dump), class: 'btn btn-default'
          - if policy(@dumps).edit?
            td = link_to :Edit, edit_brand_body_engine_ecu_dump_path(dump.ecu.engine.body.brand, dump.ecu.engine.body, dump.ecu.engine, dump.ecu, dump), class: 'btn btn-primary'
          - if policy(@dumps).destroy?
            td = link_to :Remove, brand_body_engine_ecu_dump_path(dump.ecu.engine.body.brand, dump.ecu.engine.body, dump.ecu.engine, dump.ecu, dump), method: :delete, class: 'btn btn-danger'

app/views/dumps/new.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li = link_to 'Ecus', brand_body_engine_ecus_path
  li = link_to 'Dumps', brand_body_engine_ecu_dumps_path
  li.active New

= render 'form'