config/routes.rb
Rails.application.routes.draw do
  get 'dump_table/index'
  get 'dump_table/search'
  post 'dump_table/search'

  root to: 'visitors#index'

  devise_for :users

  resources :brands do
    resources :bodies do
      resources :engines do
        resources :ecus do
          resources :dumps
        end
      end
    end
  end
end

app/models/ecu.rb
# == Schema Information
#
# Table name: ecus
#
#  id         :integer          not null, primary key
#  name       :string
#  engine_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ecu < ActiveRecord::Base
  belongs_to :engine
  has_many :dumps
  validates :name, :engine_id, presence: true
end

app/controllers/ecus_controller.rb
# == Schema Information
#
# Table name: ecus
#
#  id         :integer          not null, primary key
#  name       :string
#  engine_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EcusController < ApplicationController
  def index
    @engine = Engine.find(params[:engine_id])
    @ecus = @engine.ecus
  end

  def show
    redirect_to brand_body_engine_ecu_dumps_path params[:brand_id], params[:engine_id], params[:id]
  end

  def new
    @ecu = Ecu.new(engine: Engine.find(params[:engine_id]))
    authorize @ecu
  end

  def create
    @ecu = Ecu.new ecu_params
    authorize @ecu
    if @ecu.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @ecu = Ecu.find params[:id]
    authorize @ecu
  end

  def update
    @ecu = Ecu.find params[:id]
    authorize @ecu
    if @ecu.update ecu_params
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @ecu = Ecu.find params[:id]
    authorize @ecu
    @ecu.destroy
    redirect_to brand_body_engine_ecus_path
  end

  def ecu_params
    params.require(:ecu).permit(:name).merge(engine_id: params[:engine_id])
  end
end

app/helpers/ecus_helper.rb
# == Schema Information
#
# Table name: ecus
#
#  id         :integer          not null, primary key
#  name       :string
#  engine_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module EcusHelper
end

app/views/ecus/_form.html.slim
= simple_form_for [@ecu.engine.body.brand, @ecu.engine.body, @ecu.engine, @ecu] do |f|
  = f.input :name, label: 'Name of Ecu'
  = f.button :submit, class: 'btn-primary'

app/views/ecus/edit.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li = link_to 'Ecus', brand_body_engine_ecus_path
  li.active Update

= render 'form'

app/views/ecus/index.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path(@engine.body)
  li = link_to 'Engines', brand_body_engines_path(@engine.body.brand, @engine.body)
  li.active Ecu

.row.col-md-12
  p.lead
   => @engine.body.brand.name
   => @engine.body.name
   = @engine.name

- if policy(@ecus).create?
  .row.col-md-12
    = link_to :new, new_brand_body_engine_ecu_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Name
        th Dumps
        - if policy(@ecus).edit?
          th Edit
        - if policy(@ecus).destroy?
          th Remove
    tbody
      - for ecu in @ecus do
        tr
          td = ecu.id
          td = ecu.name
          td = link_to :Dumps, brand_body_engine_ecu_dumps_path(ecu.engine.body.brand, ecu.engine.body, ecu.engine, ecu), class: 'btn btn-default'
          - if policy(@ecus).edit?
            td = link_to :Edit, edit_brand_body_engine_ecu_path(ecu.engine.body.brand, ecu.engine.body, ecu.engine, ecu), class: 'btn btn-primary'
          - if policy(@ecus).destroy?
            td = link_to :Remove, brand_body_engine_ecu_path(ecu.engine.body.brand, ecu.engine.body, ecu.engine, ecu), method: :delete, class: 'btn btn-danger'

app/views/ecus/new.html.slim
ol.breadcrumb
  li = link_to 'Home', root_path
  li = link_to 'Brands', brands_path
  li = link_to 'Bodies', brand_bodies_path
  li = link_to 'Engines', brand_body_engines_path
  li = link_to 'Ecus', brand_body_engine_ecus_path
  li.active New

= render 'form'